version: '3'
services:
  app:
    image: blog_trujunzhang
    container_name: blog_trujunzhang
    ports:
      - 80:80
    networks:
      - web
    restart: always
  nginx:
    image: nginx
    container_name: blog_ngnix
    ports:
      - 444:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - web
    restart: always
networks:
  web:
    driver: bridge
