version: '3'
services:
  app:
    image: blog_trujunzhang
    ports:
      - 80:80
    networks:
      - web
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - web
networks:
  web:
    driver: bridge
