version: "3.9"
services:
  nextjs:
    image: blog_trujunzhang
    container_name: blog_trujunzhang
    container_name: nextjs
    ports:
      - "3000:3000"
    restart: always
  nginx:
    image: blog_nginx
    container_name: blog_nginx
    ports:
      - "80:80"
      - "444:443"
    volumes:
      - /etc/ssl/trujunzhang:/etc/nginx/ssl:ro
    restart: always